export const scopeLabels = {
	analyticsReadExtensions: "Leer analíticas de extensiones",
	analyticsReadGames: "Leer analíticas de juegos",
	bitsRead: "Leer bits",
	channelBot: "Bot de canal",
	channelManageAds: "Administrar anuncios de canal",
	channelReadAds: "Leer anuncios del canal",
	channelManageBroadcast: "Gestionar transmisiones del canal",
	channelReadCharity: "Leer información de caridad del canal",
	channelEditCommercial: "Editar comerciales del canal",
	channelReadEditors: "Leer editores del canal",
	channelManageExtensions: "Gestionar extensiones del canal",
	channelReadGoals: "Leer objetivos del canal",
	channelReadGuestStar: "Leer información de invitados destacados del canal",
	channelManageGuestStar: "Gestionar invitados destacados del canal",
	channelReadHypeTrain: "Leer información del tren de hype del canal",
	channelManageModerators: "Gestionar moderadores del canal",
	channelReadPolls: "Leer encuestas del canal",
	channelManagePolls: "Gestionar encuestas del canal",
	channelReadPredictions: "Leer predicciones del canal",
	channelManagePredictions: "Gestionar predicciones del canal",
	channelManageRaids: "Gestionar incursiones del canal",
	channelReadRedemptions: "Leer recompensas del canal",
	channelManageRedemptions: "Gestionar redenciones del canal",
	channelManageSchedule: "Gestionar horario del canal",
	channelReadStream_key: "Leer clave de transmisión del canal",
	channelReadSubscriptions: "Leer suscripciones del canal",
	channelManageVideos: "Gestionar videos del canal",
	channelReadVips: "Leer VIPs del canal",
	channelManageVips: "Gestionar VIPs del canal",
	clipsEdit: "Editar clips",
	moderationRead: "Leer moderación",
	moderatorManageAnnouncements: "Gestionar anuncios de moderadores",
	moderatorManageAutomod: "Gestionar AutoMod",
	moderatorReadAutomodSettings: "Leer configuraciones de AutoMod",
	moderatorManageAutomodSettings: "Gestionar configuraciones de AutoMod",
	moderatorManageBannedUsers: "Gestionar usuarios baneados",
	moderatorReadBlockedTerms: "Leer términos bloqueados",
	moderatorReadChatMessages: "Leer mensajes de chat",
	moderatorManageBlockedTerms: "Gestionar términos bloqueados",
	moderatorManageChatMessages: "Gestionar mensajes de chat",
	moderatorReadChatSettings: "Leer configuraciones de chat",
	moderatorManageChatSettings: "Gestionar configuraciones de chat",
	moderatorReadChatters: "Leer usuarios en el chat",
	moderatorReadFollowers: "Leer seguidores",
	moderatorReadGuestStar: "Leer información de invitados destacados",
	moderatorManageGuestStar: "Gestionar invitados destacados",
	moderatorReadModerators: "Leer moderadores",
	moderatorReadShieldMode: "Leer modo escudo",
	moderatorManageShieldMode: "Gestionar modo escudo",
	moderatorReadShoutouts: "Leer menciones",
	moderatorManageShoutouts: "Gestionar menciones",
	moderatorReadSuspiciousUsers: "Leer usuarios sospechosos",
	moderatorReadUnbanRequests: "Leer solicitudes de desbaneos",
	moderatorManageUnbanRequests: "Gestionar solicitudes de desbaneos",
	moderatorReadVips: "Leer VIPs",
	moderatorReadWarnings: "Leer advertencias",
	moderatorManageWarnings: "Gestionar advertencias",
	userBot: "Bot de usuario",
	userEdit: "Editar usuario",
	userEditBroadcast: "Editar transmisión del usuario",
	userReadBlockedUsers: "Leer usuarios bloqueados",
	userManageBlockedUsers: "Gestionar usuarios bloqueados",
	userReadBroadcast: "Leer transmisión del usuario",
	userReadChat: "Leer chat del usuario",
	userManageChatColor: "Gestionar color de chat",
	userEditEmail: "Editar correo electrónico",
	userReadEmotes: "Leer emoticonos",
	userReadFollows: "Leer seguimientos",
	userReadModeratedChannels: "Leer canales moderados",
	userReadSubscriptions: "Leer suscripciones del usuario",
	userReadWhispers: "Leer susurros",
	userManageWhispers: "Gestionar susurros",
	userWriteChat: "Escribir en el chat",
};
